# Generated by Django 5.1.2 on 2024-10-28 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_realtimestock"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockHistoryBfq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trading_date", models.DateField(verbose_name="交易日")),
                (
                    "stock_code",
                    models.CharField(max_length=20, verbose_name="股票代码"),
                ),
                ("opening_price", models.FloatField(verbose_name="开盘价")),
                ("closing_price", models.FloatField(verbose_name="收盘价")),
                ("highest_price", models.FloatField(verbose_name="最高价")),
                ("lowest_price", models.FloatField(verbose_name="最低价")),
                (
                    "trading_volume",
                    models.BigIntegerField(verbose_name="成交量(单位:手)"),
                ),
                ("trading_amount", models.FloatField(verbose_name="成交额(单位:元)")),
                ("price_range", models.FloatField(verbose_name="振幅(单位:%)")),
                (
                    "price_change_percentage",
                    models.FloatField(verbose_name="涨跌幅(单位:%)"),
                ),
                (
                    "price_change_amount",
                    models.FloatField(verbose_name="涨跌额(单位:元)"),
                ),
                ("turnover_rate", models.FloatField(verbose_name="换手率(单位:%)")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建日期"
                    ),
                ),
            ],
            options={
                "verbose_name": "股票历史记录(不复权)",
                "verbose_name_plural": "股票历史记录(不复权)",
            },
        ),
        migrations.DeleteModel(
            name="StockHistory",
        ),
        migrations.AlterModelOptions(
            name="realtimestock",
            options={
                "verbose_name": "股票实时行情",
                "verbose_name_plural": "股票实时行情",
            },
        ),
        migrations.AddField(
            model_name="realtimestock",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建日期"
            ),
        ),
        migrations.AddField(
            model_name="stockhistoryhfq",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建日期"
            ),
        ),
        migrations.AddField(
            model_name="stockhistoryqfq",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建日期"
            ),
        ),
    ]
