# Generated by Django 5.1.2 on 2024-10-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0005_tradingday_alter_realtimestock_highest_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TRADING_DAY", "交易日"),
                            ("NON_TRADING_DAY", "非交易日"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "交易日期",
                "verbose_name_plural": "交易日期",
            },
        ),
        migrations.DeleteModel(
            name="TradingDay",
        ),
    ]
