# Generated by Django 5.1.2 on 2024-11-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0006_tradingdate_delete_tradingday"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stockhistorybfq",
            constraint=models.UniqueConstraint(
                fields=("trading_date", "stock_code"),
                name="unique_trading_date_stock_code",
            ),
        ),
    ]
