# Generated by Django 5.1.2 on 2024-11-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0007_stockhistorybfq_unique_trading_date_stock_code"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stockhistorybfq",
            name="unique_trading_date_stock_code",
        ),
        migrations.AddConstraint(
            model_name="stockhistorybfq",
            constraint=models.UniqueConstraint(
                fields=("trading_date", "stock_code"),
                name="unique_trading_date_stock_code_bfq",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockhistoryhfq",
            constraint=models.UniqueConstraint(
                fields=("trading_date", "stock_code"),
                name="unique_trading_date_stock_code_hfq",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockhistoryqfq",
            constraint=models.UniqueConstraint(
                fields=("trading_date", "stock_code"),
                name="unique_trading_date_stock_code_qfq",
            ),
        ),
    ]
