# Generated by Django 5.1.2 on 2024-10-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("published_date", models.DateField()),
            ],
        ),
    ]
