# Generated by Django 5.1.2 on 2024-10-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0002_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
            ],
        ),
    ]
