# Generated by Django 5.1.2 on 2024-10-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0003_widget"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Widget",
        ),
    ]
