# Generated by Django 5.1.2 on 2024-11-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0004_delete_widget"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="book",
            constraint=models.UniqueConstraint(
                fields=("title", "author"), name="unique_title_author"
            ),
        ),
    ]
